### ISSUE TITLE
Support for mocking/stubbing components

### ISSUE THREAD

**Issue by cmelion** [turrisjs/turris-test-helpers#1]
Support for component mocks/stubs would be a nice to have.

This is an interesting approach, but I had trouble getting mocha to run with two compiler options (stub and babel):
https://github.com/danvk/mocha-react/tree/jsx-stubs
http://www.hammerlab.org/2015/02/14/testing-react-web-apps-with-mocha/

I'm currently falling back to this approach using rewire (more boiler-plate than I like):
http://substantial.com/blog/2014/11/11/test-driven-react-how-to-manually-mock-components/

Also looking into:
https://github.com/speedskater/babel-plugin-rewire

**Comment by yamalight** [comment]
@cmelion I understand mocking network requests and things like this, but why components? What would be the use cases here?

**Comment by cmelion** [comment]
@yamalight I want to test components in isolation for several reasons:
     1) Performance - top level components may load several large or deeply nested child components.
     2) Coverage - Code coverage is misleading showing coverage for components without tests.
     4) Subcomponents causing top level components tests to fail, it's a unit test not an integration test.

**Comment by yamalight** [comment]
@cmelion I don't think 1 is too much of a problem - react with jdsom is quite fast (we have some pretty huge projects with very deep nesting which are tested pretty quick).
2 and 4 on other hand sound quite good actually. will investigate the links you'd provided and see if there are any simple ways to integrate that stuff here.
And as usual, PRs are appreciated :)

**Comment by cmelion** [comment]
@yamalight I wonder what I did with #3?
I'll revisit #1 but we did have to disable a page test which loaded basically every component we had because it was timing out (still have to look into exactly what was happening) on one of our slower machines.
Also we eventually would like to get to the point where we are running test continuously during development (as we do with Karma/Angular) so shaving 100-200ms off a test suite will make a difference.

**Comment by yamalight** [comment]
@cmelion hm.. I guess the fact that we split our components into single repos helps a lot. Maybe 1) is more important if you have all of them in one repo.
I'd poked around a bit, looks like babel rewire plugin might do the trick here. Will investigate on how to properly add it to gulp tasks.

**Comment by cmelion** [comment]
@yamalight yeah separate repos would make the problem go away.  Long term I want to move components that have applicability outside the current project into their own repo.

**Comment by yamalight** [comment]
@cmelion yep, that's the way we do it - all of our components are fully reusable and are included into more than a few customer projects. works pretty well

**Comment by yamalight** [comment]
@cmelion So, after some poking around, here's what I'd found - rewire did not want to play along with babel-mocha (that plugin didn't work as well :)
But [proxyquire](https://github.com/thlorenz/proxyquire/) on other hand worked pretty much out of the box, here's and example:

``` js
/* global describe, it */
// import helpers
import should from 'turris-test-helpers';
import proxyquire from 'proxyquire';
import React from 'react';

// mock react component
const Stub = React.createClass({
    render() {
        return <span />;
    }
});
Stub['@global'] = true; // this might not be needed in your case, refer to proxyquire docs
const Component = proxyquire('../src/pages/index/index.js', {
    '../navigation': Stub,
}).IndexPage;

describe('Test component suite', function() {
    // your tests here
});
```

Added a new section of recommended libs to the Readme. Gonna close this for now.
If you still have issues - feel free to poke me.

**Comment by cmelion** [comment]
@yamalight thanks!  Mocking of sub-components is working for me.

**Comment by yamalight** [comment]
@cmelion cool, glad it worked.
